version: "3.0"
services:
  web:
    image: test/vaadin-kotlin-pwa
    ports:
      - "8080:8080"
    environment:
      - VOK_PWA_JDBC_DRIVER=org.postgresql.Driver
      - VOK_PWA_JDBC_URL=jdbc:postgresql://db:5432/postgres
      - VOK_PWA_JDBC_USERNAME=postgres
      - VOK_PWA_JDBC_PASSWORD=mysecretpassword
    links:
      - db
  db:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
